name: Docs
on: [push, pull_request]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-python@v5
      # Install plantuml
      - name: Install OS package dependencies
        run: |
          sudo apt update
          sudo apt install plantuml
          #sudo apt install npm
          #npm install mermaid
          npm install -g @mermaid-js/mermaid-cli
          #npm install markmap

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: remove unused folders
        run: |
          rm -rf docs/julia/not_used
          rm -rf docs/python/not_used
          rm -rf docs/not_used

      - name: Sphinx builds in nitpicky mode
        run: sphinx-build -n docs _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

